spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:/app/data/transport_db;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

token:
  signing:
    key: fngiasdjnfgofafwieskjntgfiu9oawerjhrnrtguiaerhnrtio4

jwt:
  access-token-expiration: 600000
  refresh-token-expiration: 604800000
